version: "3"
services:
    svr1:
        build: ./svr1
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "2500:1433"
        container_name: svr1
        hostname: sql1
    svr2:
        build: ./svr2
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "2600:1433"
        container_name: svr2
        hostname: sql2